name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    name: build
    uses: joshjohanning-org/reusable-workflows/.github/workflows/local-action-test.yml@local-action
    with:
      who-to-greet: josh
      
